/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boardWalletsSol from "./BoardWallets.sol";
export type { boardWalletsSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lib from "./lib";
export type { lib };
import type * as mocks from "./mocks";
export type { mocks };
