/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type { Errors, ErrorsInterface } from "../../../contracts/lib/Errors";

const _abi = [
  {
    inputs: [],
    name: "MATH_ADDITION_OVERFLOW",
    type: "error",
  },
  {
    inputs: [],
    name: "MATH_DIVISION_BY_ZERO",
    type: "error",
  },
  {
    inputs: [],
    name: "MATH_MULTIPLICATION_OVERFLOW",
    type: "error",
  },
  {
    inputs: [],
    name: "T_ADDRESS_ZERO",
    type: "error",
  },
  {
    inputs: [],
    name: "T_BACKUP_ADDRESS_ALREADY_EXISTS",
    type: "error",
  },
  {
    inputs: [],
    name: "T_BACKUP_ADDRESS_IS_OWNER",
    type: "error",
  },
  {
    inputs: [],
    name: "T_CANCELED",
    type: "error",
  },
  {
    inputs: [],
    name: "T_INHERITANCE_PERCENTAGE_EXCEEDED",
    type: "error",
  },
  {
    inputs: [],
    name: "T_NO_TRANSCENDENCE",
    type: "error",
  },
  {
    inputs: [],
    name: "T_SUCCEEDED",
    type: "error",
  },
  {
    inputs: [],
    name: "T_TESTAMENT_ALREADY_EXISTS",
    type: "error",
  },
  {
    inputs: [],
    name: "T_UNAUTHORIZED",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200adcd7e0cfd79c5afff0cdcae9016f8fc26e85b1db3380da9d04faf2c578556c64736f6c63430008080033";

type ErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Errors__factory extends ContractFactory {
  constructor(...args: ErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Errors> {
    return super.deploy(overrides || {}) as Promise<Errors>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Errors {
    return super.attach(address) as Errors;
  }
  override connect(signer: Signer): Errors__factory {
    return super.connect(signer) as Errors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsInterface {
    return new utils.Interface(_abi) as ErrorsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Errors {
    return new Contract(address, _abi, signerOrProvider) as Errors;
  }
}
