/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as boardWalletsSol from "./BoardWallets.sol";
export * as interfaces from "./interfaces";
export * as lib from "./lib";
export * as mocks from "./mocks";
